### ISSUE TITLE
[Request] mouse wheel scroll up and scroll down.

### ISSUE THREAD

**Issue by tohnperfect** [brookhong/brookhong.github.io#24]
Hi there,

I really love your program. 
This is not an issue the program work perfectly fine but you could make it better by displaying that the mouse wheel is scrolling up or scrolling down.

Cheers,
Tohn

**Comment by brookhong** [comment]
Supported it from 2.0.2.3.
Thanks

**Comment by PeterMinin** [comment]
Hi @brookhong, could you please explain how to enable the display of wheel events? I'm using 2.0.2.3 but scroll events don't appear.

**Comment by brookhong** [comment]
Just make sure that you have `Mouse Action` checked in settings. It will show `MouseWheelUp` or `MouseWheelDown` then.
And if you have `Mouse Only With Modifier` checked, it works only when modifier keys like Ctrl/Alt/Shift is held.

**Comment by PeterMinin** [comment]
It turned out to be my mouse settings, it only works if I switch it to "MS-IntelliMouse compatibility mode" instead of "Extended 2 wheel mode". I believe there is a way to support the extended mode too, in case you're interested, because I've also tried utilizing pyHook, and it worked with both modes.
